// Define all tags
export const registryTags = [
  "accordion",
  "alert",
  "avatar",
  "badge",
  "banner",
  "breadcrumb",
  "button",
  "calendar",
  "checkbox",
  "collapsible",
  "combobox",
  "command",
  "crop",
  "dialog",
  "dropdown",
  "input",
  "label",
  "notification",
  "otp",
  "pagination",
  "popover",
  "radio",
  "select",
  "slider",
  "sonner",
  "stepper",
  "table",
  "tabs",
  "textarea",
  "timeline",
  "switch",
  "tooltip",
  "alert dialog",
  "authentication",
  "autocomplete",
  "avatar group",
  "back",
  "card",
  "chart",
  "checkout",
  "chip",
  "color",
  "controls",
  "cookies",
  "countdown",
  "counter",
  "copy",
  "credit card",
  "darkmode",
  "date",
  "delete",
  "disabled",
  "drag and drop",
  "emblor",
  "equalizer",
  "error",
  "feedback",
  "file",
  "filter",
  "flag",
  "form",
  "gdpr",
  "hamburger",
  "helper",
  "hint",
  "hover card",
  "image",
  "info",
  "kbd",
  "like",
  "loading",
  "login",
  "mask",
  "menu",
  "modal",
  "multiselect",
  "native select",
  "newsletter",
  "next",
  "number",
  "onboarding",
  "password",
  "payment",
  "phone",
  "picker",
  "previous",
  "pricing",
  "privacy",
  "profile",
  "radix",
  "range",
  "range calendar",
  "range slider",
  "rating",
  "react aria",
  "react daypicker",
  "read-only",
  "required",
  "reset",
  "resize",
  "sale",
  "search",
  "share",
  "signup",
  "social",
  "sort",
  "status",
  "sticky",
  "subscribe",
  "success",
  "tag",
  "tanstack",
  "team",
  "text editor",
  "time",
  "timezone",
  "toast",
  "toggle",
  "toggle group",
  "tour",
  "tree",
  "upload",
  "user",
  "vertical slider",
  "vertical stepper",
  "vertical table",
  "vertical tabs",
  "vertical timeline",
  "volume",
  "vote",
  "warning",
  "week",
  "zoom",
] as const;

export type RegistryTag = (typeof registryTags)[number];

// Define registry items
export interface RegistryItem {
  name: string;
  type: string;
  title: string;
  description: string;
  files: { path: string; type: string }[];
}

export const registryItems: RegistryItem[] = [
  {
    name: "Button",
    type: "registry:component",
    title: "Button",
    description: "A reusable button component",
    files: [
      { path: "components/button/button.tsx", type: "registry:component" },
    ],
  },
  {
    name: "Card",
    type: "registry:component",
    title: "Card",
    description: "A reusable card component",
    files: [{ path: "components/card/card.tsx", type: "registry:component" }],
  },
  {
    name: "Modal",
    type: "registry:component",
    title: "Modal",
    description: "A reusable modal component",
    files: [{ path: "components/modal/modal.tsx", type: "registry:component" }],
  },
  {
    name: "Analytics",
    type: "registry:lib",
    title: "Analytics Service",
    description: "Service for tracking user interactions",
    files: [{ path: "services/analytics/analytics.ts", type: "registry:lib" }],
  },
  {
    name: "UserService",
    type: "registry:lib",
    title: "User Service",
    description: "Handles user authentication and data",
    files: [
      { path: "services/userservice/userservice.ts", type: "registry:lib" },
    ],
  },
];
